version: '3.8'


services:

  db:
    image: postgres:14
    container_name: telegram_video_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: telegram_video_bot
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_video_bot_app
    restart: unless-stopped
    depends_on:
      - db

    ports:
      - '8443:8080'

    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/telegram_video_bot}