name: Build Docker images and Deploy to cloud server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker images
      run: |
        docker compose build

    - name: Push Docker images
      run: |
        # Тегируем и пушим образы
        docker tag telegram-ai-sora-bot-app:latest ${{ secrets.DOCKER_LOGIN }}/telegram-ai-sora-bot-app:latest
        docker push ${{ secrets.DOCKER_LOGIN }}/telegram-ai-sora-bot-app:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CLOUD_SERVER_HOST }}
        port: 22
        username: ${{ secrets.CLOUD_SERVER_USERNAME }}
        password: ${{ secrets.CLOUD_SERVER_PASSWORD }}
        script: |
          cd docker/docker_containers
          docker image pull ${{ secrets.DOCKER_LOGIN }}/telegram-ai-sora-bot-app:latest
          docker stop telegram_video_bot_app || true
          docker rm telegram_video_bot_app || true
          docker compose up -d
